services:
  postgres:
    image: postgres:15-alpine
    container_name: greenandcoop_postgres
    restart: always
    environment:
      POSTGRES_DB: greenandcoop_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - greenandcoop-network

volumes:
  pgdata:

networks:
  greenandcoop-network:
    name: greenandcoop-network
